trigger:
- main

pool:
  name: 'Default' 

variables:
  imageName: 'stockkeep'
  dockerImageTag: 'latest'

jobs:
- job: BuildAndRun
  displayName: 'Build and Run Docker Image Locally on Self-Hosted Agent'
  steps:
    - checkout: self
    - script: 
        sudo docker build -t $(imageName):$(dockerImageTag) .
      displayName: 'Build Docker Image'

    - script: |
        sudo docker run -d --name $(imageName)-container $(imageName):$(dockerImageTag)  
      displayName: 'Run Docker Container'

    - script: |
        sleep 10  # Wait for 10 seconds
      displayName: 'Wait for 10 Seconds'

    - script: |
        sudo docker stop $(imageName)-container  
        sudo docker rm $(imageName)-container  
      displayName: 'Stop and Remove Docker Container'
