trigger:
- main

pool:
  name: 'Default' 

variables:
  imageName: 'stockkeep'
  dockerImageTag: 'latest'

jobs:
- job: BuildAndRun
  displayName: 'Build and Run Docker Image Locally on Self-Hosted Agent'
  steps:
    - checkout: self

    - script: |
        docker --version  # Check Docker version
        docker build -t $(imageName):$(dockerImageTag) .  # Build the Docker image
      displayName: 'Build Docker Image'

    - script: |
        echo "Working directory: $(Build.SourcesDirectory)"
      displayName: 'Output Working Directory Path'

    - script: |
        docker run -d --name $(imageName)-container $(imageName):$(dockerImageTag)  # Run Docker container in detached mode
      displayName: 'Run Docker Container'

    - script: |
        sleep 10  # Wait for 10 seconds
      displayName: 'Wait for 10 Seconds'

    - script: |
        docker stop $(imageName)-container  # Stop the Docker container
        docker rm $(imageName)-container  # Remove the Docker container
      displayName: 'Stop and Remove Docker Container'
